export enum COMMON_EVENTS {
  // User
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  SET_SESSION = 'SET_SESSION',
  CLEAR_SESSION = 'CLEAR_SESSION',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  REFRESH_USER_PROFILE = 'REFRESH_USER_PROFILE',

  // Modal
  CCC_CLOSE = 'CCC_CLOSE',
  SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL',
  CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
}
