export enum COMMON_EVENTS {
  // User
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  SET_SESSION = 'SET_SESSION',
  CLEAR_SESSION = 'CLEAR_SESSION',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  REFRESH_USER_PROFILE = 'REFRESH_USER_PROFILE',

  // Modal
  CCC_CLOSE = 'CCC_CLOSE',
  SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL',
  CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL',
  SHOW_EDIT_PROFILE_MODAL = 'SHOW_EDIT_PROFILE_MODAL',
  CLOSE_EDIT_PROFIL_MODAL = 'CLOSE_EDIT_PROFIL_MODAL',
  SHOW_TOPIC_MODAL = 'SHOW_TOPIC_MODAL',
  CLOSE_TOPIC_MODAL = 'CLOSE_TOPIC_MODAL',
  SHOW_VOTE_MODAL = 'SHOW_VOTE_MODAL',
  CLOSE_VOTE_MODAL = 'CLOSE_VOTE_MODAL',
  SHOW_STAKE_MODAL = 'SHOW_STAKE_MODAL',
  CLOSE_STAKE_MODAL = 'CLOSE_STAKE_MODAL',
  SHOW_PROPOSAL_MODAL = 'SHOW_PROPOSAL_MODAL',
  CLOSE_PROPOSAL_MODAL = 'CLOSE_PROPOSAL_MODAL',
  SHOW_BASE_DETAIL_MODAL = 'SHOW_BASE_DETAIL_MODAL',
  CLOSE_BASE_DETAIL_MODAL = 'CLOSE_BASE_DETAIL_MODAL',
  REFRESH_PROPOSAL_LIST = 'REFRESH_PROPOSAL_LIST',
  REFRESH_POPULAR_PROPOSAL_LIST = 'REFRESH_POPULAR_PROPOSAL_LIST',
  REFRESH_PREDICTION_LIST = 'REFRESH_PREDICTION_LIST',
  REFRESH_UTXO_ACTIVITY = 'REFRESH_UTXO_ACTIVITY',
  REFRESH_FORCAST_LIST = 'REFRESH_FORCAST_LIST',
  SHOW_FORCAST_MODAL = 'SHOW_FORCAST_MODAL',
  OPEN_SEARCH = 'OPEN_SEARCH',
  CLOSE_SEARCH = 'CLOSE_SEARCH'
}
