name: Deploy - DEV
run-name: 【CKB-FI-SDK-demo】${{ github.event.head_commit.message }}
on:
  workflow_dispatch:

jobs:
  deploy-frontend-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.1.2
          run_install: |
            - args: [--global, nx]

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js dependencies
        run: |
          pnpm install

      - name: Build
        env:
          VITE_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_GITHUB_SHA: ${{ github.sha }}
        run: |
          pnpm run build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_APP_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_APP_DEPLOY_ACCESS_KEY_SECRET }}
          aws-region: ap-southeast-1

      - name: Upload files to S3
        shell: bash
        run: pnpm run uploadS3 --project ckbSDKDemo --env dev --sha ${{ github.sha }}
